services:
  # Development environment
  frontend-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - network

  # Production environment
  frontend:
    profiles:
      - prod
    container_name: meetinghub-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "3001:3000"
    networks:
      - network

networks:
  network:
    external: true
