services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '6002:6001'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - network

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - '6380:6379'
    restart: unless-stopped
    networks:
      - network

volumes:
  redis_data:

networks:
  network:
    external: true
